kind: pipeline
name: linux-arm-1.0

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: julia:1.0
  commands:
      - gcc –version
      - apt-get update && apt-get install gcc-arm-linux-gnueabihf
      - uname -a
      - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("VideoIO"); Pkg.test("VideoIO"; coverage=true)'

#---
#
#kind: pipeline
#name: linux-arm-1.1
#
#platform:
#  os: linux
#  arch: arm
#
#steps:
#- name: build
#  image: julia:1.1
#  commands:
#      - uname -a
#      - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("VideoIO"); Pkg.test("VideoIO"; coverage=true)'

---

kind: pipeline
name: linux-aarch64-1.0

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: julia:1.0
  commands:
      - uname -a
      - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("VideoIO"); Pkg.test("VideoIO"; coverage=true)'

---

kind: pipeline
name: linux-aarch64-1.1

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: julia:1.1
  commands:
      - uname -a
      - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("VideoIO"); Pkg.test("VideoIO"; coverage=true)'
