name: InvalidationFlagger

on:
  - pull_request

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: nightly
      - name: Install package and precompile
        run: julia --project -e 'using Pkg;Pkg.instantiate();using VideoIO'
      - name: Test for invalidations
        run: julia --project -e 'unsafe_store!(cglobal(:jl_debug_method_invalidation, Cint), 1); using VideoIO' &> /tmp/invalidationdump.log
      - name: Parse log
        run: sed -n '/\>\>/p' /tmp/invalidationdump.log >> /tmp/invalidated.log
      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: /tmp/invalidated.log
